import { Ctmf } from "../types";

export const PROJECTS: Ctmf[] = [
  {
    slug: "stakeholder-mapping",
    title: 'Stakeholder Mapping',
    stage: 'Frame',
    subtext: 'Identified and prioritized stakeholders to understand competing needs and constraints, enabling a user-centered design frame.',
    overview: 'Stakeholder mapping helps define who is affected by a design decision, who influences the process, and where conflicting priorities are likely to surface before solutions harden too early.',
    whyItMatters: 'This CTMF keeps the work grounded in people and systems instead of letting the design brief collapse into only technical requirements.',
    evidence: [
      'Praxis I: expanded the original stakeholder set to include drafters and artists using multiple lead sizes for different tasks.',
      'Praxis II: clarified who experiences friction most directly inside the intervention system and who constrains implementation.',
      'Portfolio work: used stakeholder awareness to decide how the site should communicate process to viewers rather than only outcomes.',
    ],
    application: 'I use stakeholder mapping early to identify decision-makers, affected users, and overlooked groups, then revisit it when the project scope changes.',
  },
  {
    slug: "requirements-matrix",
    title: 'Requirements Matrix',
    stage: 'Frame',
    subtext: 'Structured functional and non-functional requirements into a traceable matrix, ensuring all design objectives were systematically addressed.',
    overview: 'A requirements matrix translates broad project goals into explicit criteria and constraints that can be checked throughout iteration rather than only at the end.',
    whyItMatters: 'It creates accountability between the original brief, what gets designed, and how a final direction is justified.',
    evidence: [
      'Praxis I: tracked dimensional, usability, and affordability requirements for the mechanical pencil concept.',
      'CIV102: aligned bridge decisions with mass, span, and load constraints that could not be negotiated away.',
      'Portfolio work: filtered content and layout choices against clarity, continuity, and reflection goals.',
    ],
    application: 'I use requirement matrices to keep decisions traceable, especially when multiple criteria compete and the team needs a clear basis for tradeoffs.',
  },
  {
    slug: "systems-thinking",
    title: 'Systems Thinking',
    stage: 'Frame',
    subtext: 'Applied holistic systems analysis to understand interdependencies between subsystems and external constraints across all projects.',
    overview: 'Systems thinking widens the frame from isolated artifacts to interactions, incentives, dependencies, and downstream effects that shape whether a design actually works in context.',
    whyItMatters: 'It prevents oversimplified problem statements and supports decisions that respond to the broader environment around a project.',
    evidence: [
      'Praxis II: centered on identifying system boundaries, leverage points, and cross-stakeholder effects before proposing an intervention.',
      'CIV102: balanced theoretical analysis with fabrication realities, material behavior, and failure modes.',
      'Portfolio work: connected separate assignments into one narrative of growth rather than treating them as disconnected deliverables.',
    ],
    application: 'I use systems thinking whenever the project outcome depends on relationships between people, materials, processes, or institutions rather than a single object alone.',
  },
  {
    slug: "scamper-method",
    title: 'SCAMPER Method',
    stage: 'Diverge',
    subtext: 'Used Substitute, Combine, Adapt, Modify, Put to other uses, Eliminate, and Reverse prompts to generate creative design alternatives.',
    overview: 'SCAMPER is a structured ideation method that forces concept generation from multiple angles so design exploration does not stall around the first plausible idea.',
    whyItMatters: 'It expands the solution space quickly and makes divergence more intentional than unstructured brainstorming alone.',
    evidence: [
      'Praxis I: helped push beyond a single modification idea toward alternate ways of storing and switching lead.',
      'Praxis II: supported exploration of intervention directions at different scales before narrowing the proposal.',
      'Portfolio work: informed experiments in sequencing atmosphere, reflection, and technical documentation.',
    ],
    application: 'I use SCAMPER when a team has identified the core problem but needs prompts that break habitual thinking and produce more varied concepts.',
  },
  {
    slug: "morphological-chart",
    title: 'Morphological Chart',
    stage: 'Diverge',
    subtext: 'Decomposed the design problem into sub-functions and systematically explored solution combinations across each dimension.',
    overview: 'Morphological charts break a design problem into functions and candidate means, making it easier to combine possibilities methodically instead of ideating in vague wholes.',
    whyItMatters: 'This CTMF turns divergence into a repeatable process and reveals combinations that might be missed in looser concept generation.',
    evidence: [
      'Praxis I: decomposed the pencil into functions like storage, selection, and feed mechanisms to compare solution combinations.',
      'CIV102: mirrored the same mindset by separating structural choices into manageable design variables.',
      'Portfolio work: helped think modularly about content sections, transitions, and supporting details.',
    ],
    application: 'I use morphological charts when a project can be decomposed into sub-functions and I want the team to explore combinations without losing structure.',
  },
  {
    slug: "brainstorming",
    title: 'Brainstorming',
    stage: 'Diverge',
    subtext: 'Facilitated structured ideation sessions with team members to generate a broad set of concepts without premature judgment.',
    overview: 'Brainstorming creates space for quantity, speed, and collaborative contribution before evaluation narrows the field.',
    whyItMatters: 'It surfaces different perspectives early and helps teams avoid converging around the loudest or most familiar idea too soon.',
    evidence: [
      'Praxis I: group ideation exposed alternative mechanisms and encouraged critique through iteration rather than personal attachment.',
      'Praxis II: discussions across multiple intervention directions helped compare different stakeholder and system responses.',
      'Portfolio work: opened up visual and narrative directions before settling on the current site structure.',
    ],
    application: 'I use structured brainstorming when the team needs shared ownership of concept generation and when rapid idea quantity is more valuable than immediate polish.',
  },
  {
    slug: "pugh-chart",
    title: 'Pugh Chart',
    stage: 'Converge',
    subtext: 'Evaluated design alternatives against a datum using structured criteria comparison, enabling objective concept selection.',
    overview: 'A Pugh chart compares alternatives against a baseline across key criteria, helping teams identify relative strengths, weaknesses, and where hybrid solutions may outperform any single concept.',
    whyItMatters: 'It introduces discipline into convergence and makes concept selection discussable, revisable, and easier to defend.',
    evidence: [
      'Praxis I: used two Pugh chart iterations with different datum choices before selecting the final direction.',
      'Praxis II: applied the same comparative logic to weigh intervention options against stakeholder fit and feasibility.',
      'Portfolio work: evaluated structural directions by coherence, readability, and evidence of growth.',
    ],
    application: 'I use Pugh charts once there are several credible concepts and the team needs a transparent method for narrowing choices without relying on preference alone.',
  },
  {
    slug: "weighted-decision-matrix",
    title: 'Weighted Decision Matrix',
    stage: 'Converge',
    subtext: 'Assigned quantified weights to design criteria and scored alternatives, providing a rigorous and transparent convergence process.',
    overview: 'Weighted decision matrices extend comparative evaluation by recognizing that not all criteria matter equally and that priorities should be made explicit.',
    whyItMatters: 'They force value judgments into the open and help a team explain why one tradeoff matters more than another.',
    evidence: [
      'Praxis I: aligned concept choice with the most critical usability and feasibility constraints.',
      'CIV102: reflected the same prioritization mindset in balancing mass against structural performance.',
      'Portfolio work: helped decide what content deserved visual emphasis and what should remain supporting material.',
    ],
    application: 'I use weighted matrices when tradeoffs are real, criteria importance differs, and the decision needs a stronger quantitative rationale.',
  },
  {
    slug: "prototyping-and-cad",
    title: 'Prototyping & CAD',
    stage: 'Represent',
    subtext: 'Created low and high-fidelity prototypes using CAD simulations and physical models to validate design decisions and communicate intent.',
    overview: 'Prototyping and CAD make ideas testable and legible, moving the design from abstraction into something that can be evaluated, explained, and improved.',
    whyItMatters: 'Representation is where assumptions become visible. Models reveal feasibility, communicate intent, and create better feedback loops.',
    evidence: [
      'Praxis I: physical and conceptual modeling helped compare mechanisms and communicate the selected design direction.',
      'CIV102: bridge construction and testing exposed the difference between calculated behavior and fabricated reality.',
      'Portfolio work: this site itself acts as a representational artifact that translates process into an accessible experience.',
    ],
    application: 'I use prototyping and CAD to turn design reasoning into forms that can be tested, critiqued, and shared with collaborators or reviewers.',
  },
];
