import type { ReferenceLibrary } from "@/app/types/references";

export const REFERENCE_LIBRARY: ReferenceLibrary = {
	"noise-learning-motivation-memory": {
		type: "article",
		year: "2007",
		title: "Effects of noise on learning, motivation and memory in young students",
		containerTitle: "Noise & Health",
		volume: "9",
		issue: "36",
		pages: "25-34",
		url: "https://pubmed.ncbi.nlm.nih.gov/18177145/",
		note: "PMID: 18177145",
		accessed: "Apr. 10, 2026",
	},
	"civ102-handout-2025": {
		type: "report",
		organization: "University of Toronto Engineering Science Program",
		year: "2025",
		month: "Oct.",
		day: "30",
		title: "CIV102 Matboard Bridge Design Project",
		publisher: "University of Toronto",
		note: "Revision 2 course handout",
		url: "/api/references/civ102-handout",
	},
	"civ102-design-report": {
		type: "report",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Project Team 202 Design Report",
		publisher: "University of Toronto",
		note: "Team design report",
		url: "/api/references/civ102/report",
		accessed: "Apr. 10, 2026",
	},
	"civ102-design-calculations": {
		type: "report",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Project Team 202 Design Calculations",
		publisher: "University of Toronto",
		note: "Calculation package supporting the bridge analysis",
		url: "/api/references/civ102/calculations",
		accessed: "Apr. 10, 2026",
	},
	"civ102-engineering-assembly": {
		type: "report",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Project Team 202 Engineering Assembly",
		publisher: "University of Toronto",
		note: "Engineering assembly package",
		url: "/api/references/civ102/assembly",
		accessed: "Apr. 10, 2026",
	},
	"civ102-final-drawings": {
		type: "report",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "Drawings for Final Design",
		publisher: "University of Toronto",
		note: "Final bridge drawing set",
		url: "/api/references/civ102/drawings",
		accessed: "Apr. 10, 2026",
	},
	"civ102-performance-summary": {
		type: "report",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Updated Performance Summary",
		note: "Project performance summary",
		url: "/api/references/civ102/performance-summary",
		accessed: "Apr. 10, 2026",
	},
	"civ102-build-review-video": {
		type: "video",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Build Review Video",
		note: "Project evidence video showing the completed bridge",
		url: "/api/references/civ102/build-review-video",
		accessed: "Apr. 10, 2026",
	},
	"civ102-bridge-testing-video": {
		type: "video",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Bridge Testing Video",
		note: "Project evidence video showing destructive testing",
		url: "/api/references/civ102/bridge-testing-video",
		accessed: "Apr. 10, 2026",
	},
	"civ102-cross-section-photo": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Final Bridge Cross-Section Photograph",
		note: "Project evidence image of the final bridge cross-section",
		url: "/api/references/civ102/cross-section",
		accessed: "Apr. 10, 2026",
	},
	"civ102-loading-configuration": {
		type: "other",
		organization: "University of Toronto Engineering Science Program",
		year: "2025",
		title: "CIV102 Loading Configuration Diagram",
		note: "Train loading schematic used in the bridge analysis package",
		url: "/api/references/civ102/loading-configuration",
		accessed: "Apr. 10, 2026",
	},
	"civ102-splice-failure-photo": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Front Splice Failure Photograph",
		note: "Project evidence image showing the governing splice failure",
		url: "/api/references/civ102/splice-failure",
		accessed: "Apr. 10, 2026",
	},
	"civ102-failure-photo": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Bridge Failure Photograph",
		note: "Project evidence image showing bridge collapse during testing",
		url: "/api/references/civ102/failure",
		accessed: "Apr. 10, 2026",
	},
	"civ102-time-log": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Team Time Log",
		note: "Project evidence image recording team hours across design and construction tasks",
		url: "/api/references/civ102/time-log",
		accessed: "Apr. 10, 2026",
	},
	"civ102-pugh-chart-1": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Pugh Chart 1",
		note: "Failure mode comparison for Design 0 and Design 1",
		url: "/api/references/civ102/pugh-1",
		accessed: "Apr. 10, 2026",
	},
	"civ102-pugh-chart-2": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Pugh Chart 2",
		note: "Failure mode comparison for Design 1 and Design 2",
		url: "/api/references/civ102/pugh-2",
		accessed: "Apr. 10, 2026",
	},
	"civ102-pugh-chart-3": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Pugh Chart 3",
		note: "Failure mode comparison for Design 2 and Design 3",
		url: "/api/references/civ102/pugh-3",
		accessed: "Apr. 10, 2026",
	},
	"civ102-pugh-chart-4": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Pugh Chart 4",
		note: "Failure mode comparison for Design 3 and Design 4.1",
		url: "/api/references/civ102/pugh-4",
		accessed: "Apr. 10, 2026",
	},
	"civ102-pugh-chart-5": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Pugh Chart 5",
		note: "Failure mode comparison for Design 4.1 and Design 4.2",
		url: "/api/references/civ102/pugh-5",
		accessed: "Apr. 10, 2026",
	},
	"civ102-pugh-chart-6": {
		type: "other",
		organization: "CIV102 Project Team 202",
		year: "2025",
		title: "CIV102 Pugh Chart 6",
		note: "Failure mode comparison for Design 4.2 and Design 4.3",
		url: "/api/references/civ102/pugh-6",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-report": {
		type: "report",
		organization: "Praxis I Team",
		year: "2025",
		title: "An Acoustically Optimized Soda-Can Opening Design",
		publisher: "University of Toronto",
		note: "Praxis I team design report",
		url: "/api/references/praxis1/report",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-alpha-release": {
		type: "report",
		organization: "Praxis I Team",
		year: "2025",
		title: "Alpha Release",
		publisher: "University of Toronto",
		note: "Praxis I concept development and early framing presentation",
		url: "/api/references/praxis1/alpha-release",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-converging-doc": {
		type: "report",
		organization: "Praxis I Team",
		year: "2025",
		title: "Converging",
		publisher: "University of Toronto",
		note: "Praxis I convergence document",
		url: "/api/references/praxis1/converging",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-reflection": {
		type: "report",
		authors: [{ given: "William", family: "Xu" }],
		year: "2025",
		title: "Praxis I Reflection Submission",
		publisher: "University of Toronto",
		note: "Individual reflection and portfolio source document",
		url: "/api/references/praxis1/reflection",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-interview-video": {
		type: "video",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Interview Video",
		note: "Project interview and stakeholder evidence video",
		url: "/api/videos/praxis1-interview",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-testing-video": {
		type: "video",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Depressurization Testing Video",
		note: "Prototype testing video used for acoustic comparison and reframing",
		url: "/api/videos/praxis1",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-slider-animation": {
		type: "video",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Slider Mechanism Animation",
		note: "Animation showing the slider-based can-opening mechanism",
		url: "/api/videos/praxis1-slider-animation",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-annotated-cad": {
		type: "other",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Annotated Slider CAD",
		note: "Annotated concept image showing the slider mechanism geometry",
		url: "/api/references/praxis1/annotated",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-morph-chart": {
		type: "other",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Morphological Chart",
		note: "Concept-generation chart from the original depressurization frame",
		url: "/api/images/praxis1-morph-chart",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-pairwise-matrix": {
		type: "other",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Pairwise Comparison Matrix",
		note: "Concept comparison matrix used before the formal Pugh chart passes",
		url: "/api/references/praxis1/pairwise",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-pugh-chart-1": {
		type: "other",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Pugh Chart Version 1",
		note: "First Pugh chart pass for early concept screening",
		url: "/api/references/praxis1/pugh-1",
		accessed: "Apr. 10, 2026",
	},
	"praxis1-pugh-chart-2": {
		type: "other",
		organization: "Praxis I Team",
		year: "2025",
		title: "Praxis I Pugh Chart Version 2",
		note: "Second Pugh chart pass for surviving concepts",
		url: "/api/references/praxis1/pugh-2",
		accessed: "Apr. 10, 2026",
	},
	"praxis2-rfp": {
		type: "report",
		organization: "Praxis II Team",
		year: "2025",
		title: "Addressing the Dexterity-Manipulability Gap Experienced by Amateur Astronomers in Cold Weather",
		publisher: "University of Toronto",
		note: "Praxis II Request For Proposals document",
		url: "/api/references/praxis2/rfp",
		accessed: "Apr. 11, 2026",
	},
	"praxis2-beta-release": {
		type: "report",
		organization: "Praxis II Team",
		year: "2025",
		title: "BETA Release",
		publisher: "University of Toronto",
		note: "Praxis II interim project presentation showing early framing, concept directions, and testing logic",
		url: "/api/references/praxis2/beta",
		accessed: "Apr. 11, 2026",
	},
	"praxis2-showcase-doc": {
		type: "report",
		organization: "Praxis II Team",
		year: "2025",
		title: "Praxis II Showcase Document",
		publisher: "University of Toronto",
		note: "Final showcase source document for requirements, testing, prototype rationale, and final solution explanation",
		url: "/api/references/praxis2/showcase",
		accessed: "Apr. 11, 2026",
	},
	"praxis2-discord-record": {
		type: "other",
		organization: "Praxis II Team",
		year: "2025",
		title: "Praxis II Discord Record",
		note: "Team process record documenting discussion of scope, research, validation, and concept-development decisions",
		url: "/api/references/praxis2/discord",
		accessed: "Apr. 11, 2026",
	},
	"praxis2-one-pager": {
		type: "report",
		organization: "Praxis II Team",
		year: "2025",
		title: "Praxis II One-Pager",
		note: "One-page project summary used to communicate project framing, requirements, and evaluation logic",
		url: "/api/images/praxis2-one-pager/front",
		accessed: "Apr. 11, 2026",
	},
	"praxis2-final-poster": {
		type: "other",
		organization: "Praxis II Team",
		year: "2025",
		title: "Praxis II Final Poster Board",
		note: "Final poster board summarizing the problem framing, prototype, testing, and solution rationale",
		url: "/api/references/praxis2/poster",
		accessed: "Apr. 11, 2026",
	},
	"toronto-sun-december-timeanddate": {
		type: "web",
		organization: "Time and Date AS",
		year: "2026",
		title: "Toronto, Ontario, Canada - Sunrise, Sunset, and Daylength, December 2026",
		publisher: "timeanddate.com",
		url: "https://www.timeanddate.com/sun/canada/toronto?month=12",
		accessed: "Apr. 11, 2026",
	},
	"toronto-climate-normals-1991-2020": {
		type: "web",
		organization: "Environment and Climate Change Canada",
		year: "2026",
		title: "Canadian Climate Normals 1991-2020 Data: Toronto (City), Ontario",
		publisher: "Government of Canada",
		url: "https://climate.weather.gc.ca/climate_normals/results_1991_2020_e.html?climate_id=6158350&dispBack=0&searchMethod=contains&searchType=stnName_1991&txtCentralLatMin=0&txtCentralLatSec=0&txtCentralLongMin=0&txtCentralLongSec=0&txtStationName_1991=toronto",
		accessed: "Apr. 11, 2026",
	},
	"kool-aid-jammers-product": {
		type: "web",
		organization: "Kraft Heinz",
		title: "Jammers, Blue Raspberry",
		publisher: "Kraft Heinz Canada",
		url: "https://www.kraftheinz.com/en-CA/koolaid/products/00066188070907-jammers",
		note: "Official Kool-Aid Jammers product page describing straw-in-pouch use.",
		accessed: "Apr. 11, 2026",
	},
};
