import * as THREE from "three";
import { WorkTimelinePoint } from "../types";

export const WORK_TIMELINE: WorkTimelinePoint[] = [
  {
    point: new THREE.Vector3(0, 0, 0),
    year: 'Sep 2025',
    title: 'Praxis I',
    subtitle: 'Design & Innovation',
    position: 'right',
    slug: 'praxis-i',
    focusProgress: 0,
    focusWidth: 0.05,
    overlayLeft: 880,
    overlayTop: 441,
    overlayWidth: 495,
    overlayHeight: 251,
  },
  {
    point: new THREE.Vector3(-4, -4, -3),
    year: 'Nov 2025',
    title: 'CIV102 Bridge',
    subtitle: 'Structural Engineering',
    position: 'left',
    slug: 'civ102-bridge',
    focusProgress: 0.3,
    focusWidth: 0.05,
    overlayLeft: 457,
    overlayTop: 509,
    overlayWidth: 618,
    overlayHeight: 374,
  },
  {
    point: new THREE.Vector3(-3, -1, -6),
    year: 'Jan 2026',
    title: 'Praxis II',
    subtitle: 'Systems Intervention',
    position: 'left',
    slug: 'praxis-ii',
    focusProgress: 0.52,
    focusWidth: 0.05,
    overlayLeft: 449,
    overlayTop: 469,
    overlayWidth: 541,
    overlayHeight: 279,
  },
  {
    point: new THREE.Vector3(0, -1, -10),
    year: 'Mar 2026',
    title: 'Portfolio',
    subtitle: 'Reflection & Growth',
    position: 'left',
    slug: 'portfolio',
    selectable: false,
    focusProgress: 0.76,
    focusWidth: 0.05,
    overlayLeft: 514,
    overlayTop: 457,
    overlayWidth: 474,
    overlayHeight: 261,
  },
  {
    point: new THREE.Vector3(1, 1, -12),
    year: 'Beyond',
    title: '???',
    subtitle: 'Still forming',
    position: 'right',
    slug: 'beyond',
    selectable: false,
    displayOnly: true,
    focusProgress: 1,
    focusWidth: 0.04,
    overlayLeft: 934,
    overlayTop: 468,
    overlayWidth: 156,
    overlayHeight: 97,
  }
]
